version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install

    