version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-stretch
    working_directory: ~/app 
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Build app
          command: npm build
  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/app
    steps:
      - run:
          name: Build Docker image
          command: docker build --file .circleci/images -t test-vue .
    

    