version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: docker build -t testci

    