version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: docker build -t test .

    