version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-stretch
    working_directory: ~/app 
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install

    